ENG_COUNTRIES = {
    "a": [
        "afghanistan",
        "albania",
        "algeria",
        "andorra",
        "angola",
        "antigua and barbuda",
        "argentina",
        "armenia",
        "australia",
        "austria",
        "azerbaijan",
        "abkhazia",
    ],
    "b": [
        "bahamas",
        "bahrain",
        "bangladesh",
        "barbados",
        "belarus",
        "belgium",
        "belize",
        "benin",
        "bhutan",
        "bolivia",
        "bosnia and herzegovina",
        "botswana",
        "brazil",
        "brunei",
        "bulgaria",
        "burkina faso",
        "burundi",
    ],
    "c": [
        "cambodia",
        "cameroon",
        "canada",
        "cape verde",
        "central african republic",
        "chad",
        "chile",
        "china",
        "colombia",
        "comoros",
        "costa rica",
        "croatia",
        "cuba",
        "cyprus",
        "czech republic",
        "cook islands",
    ],
    "h": ["hong kong", "haiti", "honduras", "hungary"],
    "m": [
        "macao",
        "madagascar",
        "malawi",
        "malaysia",
        "maldives",
        "mali",
        "malta",
        "marshall islands",
        "mauritania",
        "mauritius",
        "mexico",
        "micronesia",
        "moldova",
        "monaco",
        "mongolia",
        "montenegro",
        "morocco",
        "mozambique",
        "myanmar",
    ],
    "d": [
        "democratic republic of the congo",
        "denmark",
        "djibouti",
        "dominica",
        "dominican republic",
    ],
    "r": ["republic of the congo", "romania", "russia", "rwanda"],
    "f": ["faroe islands", "fiji", "finland", "france"],
    "g": [
        "greenland",
        "gabon",
        "gambia",
        "georgia",
        "germany",
        "ghana",
        "greece",
        "grenada",
        "guatemala",
        "guinea",
        "guinea-bissau",
        "guyana",
    ],
    "e": [
        "east timor",
        "ecuador",
        "egypt",
        "el salvador",
        "equatorial guinea",
        "eritrea",
        "estonia",
        "eswatini",
        "ethiopia",
    ],
    "i": [
        "iceland",
        "india",
        "indonesia",
        "iran",
        "iraq",
        "ireland",
        "israel",
        "italy",
        "ivory coast",
    ],
    "j": ["jamaica", "japan", "jordan"],
    "k": ["kazakhstan", "kenya", "kiribati", "kuwait", "kyrgyzstan"],
    "l": [
        "laos",
        "latvia",
        "lebanon",
        "lesotho",
        "liberia",
        "libya",
        "liechtenstein",
        "lithuania",
        "luxembourg",
    ],
    "n": [
        "namibia",
        "nauru",
        "nepal",
        "netherlands",
        "new zealand",
        "niue",
        "nicaragua",
        "niger",
        "nigeria",
        "north korea",
        "north macedonia",
        "norway",
        "northern cyprus",
    ],
    "o": ["oman"],
    "p": [
        "pakistan",
        "palau",
        "palestine",
        "panama",
        "papua new guinea",
        "paraguay",
        "peru",
        "philippines",
        "poland",
        "portugal",
    ],
    "q": ["qatar"],
    "s": [
        "saint kitts and nevis",
        "saint lucia",
        "saint vincent and the grenadines",
        "samoa",
        "san marino",
        "sao tome and principe",
        "saudi arabia",
        "senegal",
        "serbia",
        "seychelles",
        "sierra leone",
        "singapore",
        "slovakia",
        "slovenia",
        "solomon islands",
        "somalia",
        "south africa",
        "south korea",
        "south sudan",
        "spain",
        "sri lanka",
        "sudan",
        "suriname",
        "sweden",
        "switzerland",
        "syria",
        "sahrawi arab democratic republic",
        "somaliland",
        "south ossetia",
    ],
    "t": [
        "tajikistan",
        "tanzania",
        "thailand",
        "togo",
        "tonga",
        "trinidad and tobago",
        "tunisia",
        "turkey",
        "turkmenistan",
        "tuvalu",
        "taiwan",
        "transnistria",
    ],
    "u": [
        "uganda",
        "ukraine",
        "united arab emirates",
        "united kingdom",
        "united states",
        "uruguay",
        "uzbekistan",
    ],
    "v": ["vanuatu", "vatican city", "venezuela", "vietnam"],
    "y": ["yemen"],
    "z": ["zambia", "zimbabwe"],
}
